Update might fail with 'apt upgrade'
Tested on Ubuntu Server 20.04

When mariadb is updated in the same `apt upgrade`-run as passbolt then the database upgrade fails.
```
Setting up passbolt-ce-server (3.8.1-1) ...
Installing new version of config file /etc/passbolt/app.default.php ...
Installing new version of config file /etc/passbolt/app.php ...
Installing new version of config file /etc/passbolt/bootstrap.php ...
Installing new version of config file /etc/passbolt/default.php ...
Installing new version of config file /etc/passbolt/routes.php ...
Installing new version of config file /etc/passbolt/version.php ...

     ____                  __          ____
    / __ \____  _____ ____/ /_  ____  / / /_
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /
 /_/    \__,_/____/____/_.___/\____/_/\__/

 Open source password manager for teams
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
 Running migration scripts.
-------------------------------------------------------------------------------
using migration paths
 - /etc/passbolt/Migrations
using seed paths
 - /etc/passbolt/Seeds
Exception: There was a problem connecting to the database: SQLSTATE[HY000] [2002] Connection refused
In [/usr/share/php/passbolt/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php, line 96]

dpkg: error processing package passbolt-ce-server (--configure):
 installed passbolt-ce-server package post-installation script subprocess returned error exit status 1
```
So passbolt upgade should be triggered before the remaining system.